[package]
name = "fix-to-kafka"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
babelfix = { workspace = true, features = [ "serde" ] }
tokio.workspace = true
anyhow.workspace = true
futures.workspace = true
tokio-util.workspace = true
tracing.workspace = true
bytes.workspace = true

kv = { version = "0.24", features = [ "bincode-value" ] }
samsa = "0.1.8"
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
serde_json = "1.0.151"
serde_with = "3.17.0"
