services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=external://0.0.0.0:9092,internal://0.0.0.0:19092
      - --advertise-kafka-addr=external://localhost:9092,internal://redpanda:19092
    ports:
      - "9092:9092"
      - "9644:9644"   # admin API (optional)
  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "9093:8080"

    depends_on:
      - redpanda
    environment:
      - KAFKA_BROKERS=redpanda:19092
